[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "app"

[services.variables]
PORT = "5000"
FLASK_ENV = "production"
PYTHONPATH = "/app"
